create_sending-messages
KarenShinozaki/chat-space pull request #7
Opened 2019-03-14 15:58 UTC by KarenShinozaki

# WHAT
メッセージ送信機能の実装
# WHY
アプリとして、メッセージを送信し、送ったメッセージを確認できる必要があるため。

2019-03-15 06:37 UTC, takebn26 requested changes
よく書けていて嬉しいです

2019-03-15 06:37 UTC, takebn26 commented on app/controllers/messages_controller.rb
> +    @message = @group.messages.new(message_params)
@group.messagesではなくて
今回はcurrent_user.messages.newの方が良さそう
なぜなら、
groupのidはパス(/groups/1/messages)からparams[:groups_id]として取得できるから

2019-03-15 06:37 UTC, takebn26 commented on app/controllers/messages_controller.rb
> +    @message = Message.new
これは
current_user.messages.new
で生成すれば下の修正と合わせて
set_messageメソッドを定義して
before_actionで定義できそう

2019-03-15 06:37 UTC, takebn26 commented on app/controllers/messages_controller.rb
> +    @message = @group.messages.new(message_params)
この修正をしたら
indexアクションでしか使わないから
set_groupメソッドを定義する必要がなくなるかな？

2019-03-15 06:37 UTC, takebn26 commented on app/controllers/messages_controller.rb
> +      flash.keep[:alert] = 'メッセージを入力して下さい'
よく考えました

2019-03-15 06:37 UTC, takebn26 commented on app/controllers/messages_controller.rb
> +    params.require(:message).permit(:body, :image, :id).merge(user_id: current_user.id)
ここは上の修正と合わせて
mergeさせるのはparams[:group_idにしよう]

```
params.require(:message).permit(:body, :image, :id)
```
の `:id` は省略できる

2019-03-15 06:37 UTC, takebn26 commented on app/uploaders/image_uploader.rb
> +  # def extension_whitelist
これはあってもいいかな

2019-03-15 06:37 UTC, takebn26 commented on app/uploaders/image_uploader.rb
> +  def store_dir
このメソッドか何をするものなのか
このコメントに返信しといて

2019-03-15 06:37 UTC, takebn26 commented on app/views/groups/_group_header.html.haml
> +      .chat__header__detail__member Member : #{@group.users.pluck(:name).join(' ')}
pluck .joinいいね
pluckはもう一度定義を確認しておこう
こういうrubyの便利メソッドはたくさんあるからrubyの公式でよく見ておくといいよ
https://docs.ruby-lang.org/ja/2.6.0/doc/index.html

2019-03-15 06:37 UTC, takebn26 commented on app/views/messages/index.html.haml
> += render 'groups/sidebar'
messagesのindexにも使うなら
groupsディレクトリに入れておくのはおかしいかな

こういう別のコントローラーのビューで使うものは
sharedディレクトリを作ってそこに格納しよう

2019-03-15 06:37 UTC, takebn26 commented on app/views/messages/index.html.haml
> += render 'form'
formとcontent逆な気がする

group_headerとformとcontentは部分テンプレートにしなくてもいいんじゃないかな
ここにそのまま書いてもいい気がする

2019-03-15 06:37 UTC, takebn26 commented on app/uploaders/image_uploader.rb
> +  # end
いらないコメントアウトは全て消そう

2019-03-15 06:37 UTC, takebn26 commented on app/views/groups/index.html.haml
> += render 'sidebar'
sharedディレクトリにsidebarは格納して呼び出そう

2019-03-15 06:37 UTC, takebn26 commented on app/controllers/messages_controller.rb
> +    if @message.save
if文から成功失敗判定の意味になるから
if文の上に一行空行開けるとより意味がわかりやすくなるね

例
```
def create
  # 初期化
  @message = Message.new(message_params)

  # 一行あけて成功失敗判定
  if @message.save
  else
  end
end 
```

こんな感じで意味の塊に応じて空行を入れよう

2019-03-15 06:37 UTC, takebn26 commented on app/controllers/messages_controller.rb
> +  def message_params
privateの下は慣習的に空行一つ開ける

2019-03-15 06:37 UTC, takebn26 commented on app/views/messages/_form.html.haml
> +    = f.submit 'send',class: 'chat__text__submit-btn'
カンマのあと半角スペース

2019-03-15 09:44 UTC, KarenShinozaki commented on app/views/messages/_form.html.haml
> +    = f.submit 'send',class: 'chat__text__submit-btn'
直しました

2019-03-15 09:44 UTC, KarenShinozaki commented on app/views/messages/index.html.haml
> += render 'groups/sidebar'
わかりました

2019-03-15 09:44 UTC, KarenShinozaki commented on app/views/groups/index.html.haml
> += render 'sidebar'
直しました

2019-03-15 09:44 UTC, KarenShinozaki commented on app/views/messages/index.html.haml
> += render 'form'
わしがせっかく分化した部分テンプレート、、、、、、、、、、、、

2019-03-15 09:44 UTC, KarenShinozaki commented on app/views/messages/index.html.haml
> += render 'form'
group_headerは、分化しないと、サイドバーに一緒に表示されちゃうので、messageがクリックした時に一緒に表示させたいものだったので、分化しちゃいました。

2019-03-15 10:09 UTC, KarenShinozaki commented on app/uploaders/image_uploader.rb
> +  def store_dir
ファイルの保存先を指定しているメソッドです。
modelがモデルで、mounted_asがカラム指定です

2019-03-15 10:09 UTC, KarenShinozaki commented on app/uploaders/image_uploader.rb
> +  # def extension_whitelist
はい

2019-03-15 10:09 UTC, KarenShinozaki commented on app/controllers/messages_controller.rb
> +    @message = Message.new
直しました。確認お願いします

2019-03-15 10:09 UTC, KarenShinozaki commented on app/controllers/messages_controller.rb
> +    @message = @group.messages.new(message_params)
すみません意図を勘違いしていました。
よろしくお願いいたします。

2019-03-15 11:11 UTC, takebn26 requested changes

2019-03-15 11:11 UTC, takebn26 commented on app/views/messages/_message.html.haml
> +    = message.created_at
これいまのところ変な時間出てると思うから
綺麗にしてほしい！
調べてやってみて

2019-03-15 11:38 UTC, takebn26 requested changes

2019-03-15 11:38 UTC, takebn26 commented on app/views/messages/index.html.haml
> +.chat__text
これマークアップの時の階層と合ってる？？

2019-03-15 12:00 UTC, KarenShinozaki commented on app/views/messages/_message.html.haml
> +    = message.created_at
やりました！

2019-03-15 12:00 UTC, KarenShinozaki commented on app/views/messages/index.html.haml
> +.chat__text
こうじゃないと治らなかったです、、

2019-03-15 12:06 UTC, KarenShinozaki commented on app/views/messages/index.html.haml
> +.chat__text
嘘です

2019-03-15 12:06 UTC, KarenShinozaki commented on app/views/messages/index.html.haml
> +.chat__text
綺麗に直しました

2019-03-21 13:56 UTC, KarenShinozaki commented
https://gyazo.com/4b9165b4384a6fd486fa05187e74dcfa

2019-03-28 10:19 UTC, merged